### ISSUE TITLE
Invalid lang format.

### ISSUE THREAD

**Issue by danmarsden** [sharpchi/moodle-tool_modedit#1]
string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by danmarsden** [comment]
@sharpchi - I see the commit that fixes this, but doesn't look like you remember to close this issue off? :-)

**Comment by sharpchi** [comment]
Fixed
